### ISSUE TITLE
KeyError: 'year'

### ISSUE THREAD

**Issue by onedr0p** [KurzonDax/Plex-to-InfluxDB-Extended#10]
I am using the Docker container, this was working fine a few hours ago. Not sure what is happening here...

```
5/20/2018 12:02:27 AMLoading Configuration File /plexdata/config.ini
5/20/2018 12:02:27 AMINFO: Found 0 Bad Server(s).  Removing Them From List
5/20/2018 12:02:27 AMConfiguration Successfully Loaded
5/20/2018 12:02:32 AMTraceback (most recent call last):
5/20/2018 12:02:32 AM  File "/plexdata/plexInfluxdbCollector.py", line 730, in <module>
5/20/2018 12:02:32 AM    main()
5/20/2018 12:02:32 AM  File "/plexdata/plexInfluxdbCollector.py", line 726, in main
5/20/2018 12:02:32 AM    collector.run()
5/20/2018 12:02:32 AM  File "/plexdata/plexInfluxdbCollector.py", line 602, in run
5/20/2018 12:02:32 AM    self.get_active_streams()
5/20/2018 12:02:32 AM  File "/plexdata/plexInfluxdbCollector.py", line 205, in get_active_streams
5/20/2018 12:02:32 AM    self._process_active_streams(active_streams)
5/20/2018 12:02:32 AM  File "/plexdata/plexInfluxdbCollector.py", line 326, in _process_active_streams
5/20/2018 12:02:32 AM    if stream.attrib['year'] is not None:
5/20/2018 12:02:32 AMKeyError: 'year'
```

**Comment by KurzonDax** [comment]
Are you using the container downloaded from the docker hub or are you building the container with the Dockerfile?

The reason I'm asking is there was definitely a bug in one of the initial container builds with the year field so you may need to pull the container again ( or build it again if you're using the Dockerfile) to get the most recent update.

In any case, I thought I had stomped the bug with the year field, but it's possible I missed something.  By chance, do you know what type of media was playing when then error happened (e.g. TV Show, Movie, Music, etc)?  If not, no worries.  I will take a look at it again and see if I can find a scenario that I might have missed.

**Comment by onedr0p** [comment]
I am using `:latest` in docker hub. I didn't capture what was playing it must have been a movie or tv show because I do not have music in Plex.

**Comment by KurzonDax** [comment]
Ok, cool.  I took a quick look at the script earlier today and I may have an idea on how to prevent it from bombing out.  I'll do some testing tonight.

One other quick question: does the container now stop every time something plays on Plex?  If so, it's possible the script wrote something funky to one of the fields in the Influx database.  If this is the case, you may have to drop the plexdata database from Influx and let the script recreate it (or recreate it manually if you want a custom retention policy).  I'm definitely going to add some logic to ensure this doesn't happen in the future.

Dropping the database is pretty easy.  If you aren't familiar with how to do it, here are some quick instructions (this assumes you're running Docker on a linux host):

From a shell prompt:
```bash
sudo docker exec -it <name of your influx container> influxdb
```
This will put you at an InfluxDB prompt.  It should look similar to this:
```
Connected to http://localhost:8086 version 1.5.2
InfluxDB shell version: 1.5.2
>
```
If you are using security with influx, you'll need to authorize as your administrative user by entering
```auth <username> <password>``` at the prompt.

Then it's just dropping the database and quitting.  If you specified a different database name in the config.ini for the script, just change the plexdata to whatever you named the database.
```
DROP DATABASE "plexdata"
quit
```

**Comment by KurzonDax** [comment]
Ok, I think it should be fixed now.  It was a dumb mistake in the Python script.  An updated image is being built now on Docker hub, so it should be available in the next 10-15 minutes or so.

Let me know if you any problems with it.   I tried testing against as many different types of content as possible to see if I could make it fail, but it seemed solid.  I'll leave this issue open for a few days to be sure.

**Comment by onedr0p** [comment]
It's been running for the past 24hr without any problems. I'll report back if anything arises.

Thanks!
